on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy-to-both
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Passo 1: Envia para o Nekoweb
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'ulon.dev'
          nekoweb-username: 'ulon'
          directory: 'website'

      # Passo 2: Envia para o Neocities
      - name: deploy2neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_TOKEN }}
          dist_dir: 'website'
          cleanup: false
          neocities_supporter: false
          preview_before_deploy: true